### ISSUE TITLE
Fix milestone-0.0.1 error

### ISSUE THREAD

**Issue by hoonsubin** [TeamSTEP/Catch.ioProjectBoard#8]
## Required Tasks:
- [x] move-point is NaN.
- [x] object bounce off the wall
- [x] lighting manager exist two object.

## Description:
error.
move-point is NaN.

cause.
no value during root calculation when calculating move-point.

conjecture solution.
I

///////////////////////////////////////////////

lack.
object bounce off the wall

conjecture solution.
if object hit the wall, than re calculate move-point and move-sequence. 
To do that, have to recalculate the power and direction of the player.

///////////////////////////////////////////////

error.
lighting-manager exist two object.

cause.
this error is only occur when manager-scene is loaded before level-scene.

conjecture solution.
Edit lighting-manager Singleton pattern.

///////////////////////////////////////////////
